# permissions for end users to view datasources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datasource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dbhero
    app.kubernetes.io/part-of: dbhero
    app.kubernetes.io/managed-by: kustomize
  name: datasource-viewer-role
rules:
- apiGroups:
  - datasource.dbhero.io
  resources:
  - datasources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datasource.dbhero.io
  resources:
  - datasources/status
  verbs:
  - get
