---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.dbhero.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.dbhero.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - database.dbhero.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - datasource.dbhero.io
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datasource.dbhero.io
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - datasource.dbhero.io
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
