pipeline {
  agent {
      label 'db'
  }
  stages {
    stage('checklist') {
      agent {
          label 'db'
      }
      steps {
          sh 'go version'
          sh 'printenv'
      }
    }

    stage('Pull source code') {
      agent {
          label 'db'
      }
      steps {
        sh 'id'
        git(
            url: env.GIT_URL,
            credentialsId: env.GITLAB_CREDENTIAL_ID,
            branch: env.DEPLOY_ENV,
            changelog: true,
            poll: false
        )
        sh 'pwd'
        sh 'ls -al'
        sh 'cat Dockerfile'
      }
    }

    stage('Compile source code') {
      agent {
          label 'db'
      }
      steps {
          sh 'cat Dockerfile'
          withCredentials([usernamePassword(credentialsId : env.HARBOR_CREDENTIAL_ID ,passwordVariable : 'HARBOR_PASSWORD' ,usernameVariable : 'HARBOR_USERNAME' ,)]) {
            sh 'echo $HARBOR_USERNAME'
            sh 'echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" --password-stdin $REGISTRY'
            sh 'docker build --network host -t $REGISTRY/$PROJECT/$DEPLOY_APP:$DEPLOY_ENV-$BUILD_NUMBER .'
            sh 'docker push $REGISTRY/$PROJECT/$DEPLOY_APP:$DEPLOY_ENV-$BUILD_NUMBER'
          }
      }
    }

    stage('deploy') {
      agent {
          label 'db'
      }
      steps {
            sh 'make manifests'
            sh 'make install'
            sh 'IMG=$REGISTRY/$PROJECT/$DEPLOY_APP:$DEPLOY_ENV-$BUILD_NUMBER make docker-build'
            sh 'IMG=$REGISTRY/$PROJECT/$DEPLOY_APP:$DEPLOY_ENV-$BUILD_NUMBER make docker-push'
            sh 'make deploy'
        }
    }

    environment {
        GIT_URL = 'https://git.onecode.cmict.cloud/cpsyb/onecodepingtaituandui/dbaasGroup/dbaas.git'
        KUBECONFIG_CREDENTIAL_ID = 'kubeconfig'
        GITLAB_CREDENTIAL_ID = 'gitid'
        HARBOR_CREDENTIAL_ID = 'harborid'
        REGISTRY = 'image.onecode.cmict.cloud'
        PROJECT = 'common'
        DEPLOY_APP = 'dbhero-controller'
        DEPLOY_ENV = 'main'
    }
}
